# Generated by Django 5.0 on 2024-01-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas',
            old_name='data_reserva',
            new_name='data_pgto_reserva',
        ),
        migrations.RenameField(
            model_name='reservas',
            old_name='valor_total',
            new_name='saldo_a_pagar',
        ),
        migrations.AddField(
            model_name='reservas',
            name='valor_total_diarias',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name='reservas',
            name='vl_pgto_reserva',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
